name: Run Pytest for Voice Ordering System

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update && sudo apt-get install -y ffmpeg  # required for Whisper

    - name: Flatten audio folder structure
      run: |
        find sample_audios -mindepth 2 -type f \( -iname "*.wav" -o -iname "*.ogg" \) -exec mv -t sample_audios {} +

    - name: Run pytest
      run: |
        pytest -v tests/test_main.py
